imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
#    http_method_override: false
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        completehost: %completehost%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SGN\UserBundle\Entity\User

elsass_seeraiwer_es_bar:
    toolbar: true
    classname: navbar-fixed-top
    innerclassname: container
    locale_tool: true
    registration: false
    templates:
        - { name: "home", next:false, template: "SGNDevBlogBundle:ESBar:homeBar.html.twig" }
#        - { name: "menu", template: "SGNTemplateBundle:DevBlog:esBarMenu.html.twig" }
        - { name: "esmenu", template: "ElsassSeeraiwerESMenuBundle:ESBar:esmenuBar.html.twig", parameters:{'authorized_role': 'ROLE_MENU'} }
        - { name: "translation", template: "JMSTranslationBundle:ESBar:translationBar.html.twig", parameters:{'authorized_role': 'ROLE_TRANSLATION'} }
        - { name: "article", template: "ElsassSeeraiwerESArticleBundle:ESBar:articleBar.html.twig", parameters:{'authorized_role': 'ROLE_DEV'} }

elsass_seeraiwer_es_article:
    locales: ['fr', 'en']
    default_authorized_role:  ROLE_DEV
    tagpath: 'sgn_devblog_blog_tags_1'
    tinymce: 
        content_css: 
            - "%completehost%/bundles/sgntemplate/css/bootstrap-2.3.2/bootstrap.min.css"
            - "%completehost%/bundles/sgntemplate/css/bootstrap-2.3.2/bootstrap-responsive.min.css"
            - "%completehost%/bundles/sgntemplate/css/devblog.css"
            # - 'http://localhost/WebITRF/web/bundles/itrfwebsite/css/itrf.css'
        plugin: "code hr link table save anchor searchreplace fullscreen charmap visualblocks image media nonbreaking autolink advlist contextmenu"
        toolbar1: "save | undo redo | removeformat | styleselect | fullscreen | cut copy paste | searchreplace | hr anchor link table charmap visualblocks nonbreaking"
        toolbar2: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent blockquote | subscript superscript"
        contextmenu: "bold italic underline strikethrough | link image inserttable | cell row column deletetable"
        tools: "inserttable"
        nonbreaking_force_tab: true
        save_enablewhendirty: true
        # Le symbole "|" sur la première ligne est très important !! Il permet de predre la suite pour une chaine et non du contenu YML et de préserver les saut de ligne.
        style_formats: |
            [
                {title: 'Titre 1', block: 'h2'},
                {title: 'Titre 2', block: 'h3'},
                {title: 'Titre 3', block: 'h4'},
                {title: 'Paragraphe normal', block: 'p'},
                {title: 'Error', block: 'div', classes: 'alert alert-error'},
                {title: 'Warning', block: 'div', classes: 'alert alert-block'},
                {title: 'Success', block: 'div', classes: 'alert alert-success'},
                {title: 'Info', block: 'div', classes: 'alert alert-info'},
                {title: 'Label Default', block: 'span', classes: 'label'},
                {title: 'Label Success', block: 'span', classes: 'label label-success'},
                {title: 'Label Warning', block: 'span', classes: 'label label-warning'},
                {title: 'Label Important', block: 'span', classes: 'label label-important'},
                {title: 'Label Info', block: 'span', classes: 'label label-info'},
                {title: 'Label Inverse', block: 'span', classes: 'label label-inverse'},
                {title: 'Badges Default', block: 'span', classes: 'badge'},
                {title: 'Badges Success', block: 'span', classes: 'badge badge-success'},
                {title: 'Badges Warning', block: 'span', classes: 'badge badge-warning'},
                {title: 'Badges Important', block: 'span', classes: 'badge badge-important'},
                {title: 'Badges Info', block: 'span', classes: 'badge badge-info'},
                {title: 'Badges Inverse', block: 'span', classes: 'badge badge-inverse'}
            ]
#                {title: 'Pretty Code', block: 'xmp', classes: 'prettyprint lang-php linenums'}

jms_translation:
    locales: [fr, en]
    tinymce_mod: []
    configs:
        app:
            dirs: ['@SGNDevBlogBundle']
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: [*TestCase.php, *Test.php, *.php]
            excluded_dirs: [cache, data, logs]
            default_output_format: xliff
            keep: true
            # extractors: [alias_of_the_extractor]

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable:  true
            tree:       true

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension