imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
#    - { resource: "@ElsassSeeraiwerESBarBundle/Resources/config/toolbar.xml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
#    http_method_override: false
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: ElsassSeeraiwer\ESDemoBundle\Entity\User

elsass_seeraiwer_es_bar:
    toolbar: true
    locale_tool: true
    registration: true
    templates:
        - { name: "home", next:false, template: "ElsassSeeraiwerESDemoBundle:ESBar:homeBar.html.twig" }
        - { name: "translation", template: "JMSTranslationBundle:ESBar:translationBar.html.twig", parameters:{'authorized_role': 'ROLE_SUPER_ADMIN'} }
        - { name: "article", template: "ElsassSeeraiwerESArticleBundle:ESBar:articleBar.html.twig", parameters:{'authorized_role': 'ROLE_SUPER_ADMIN'} }

elsass_seeraiwer_es_article:
    locales: ['en', 'fr']
    tinymce: 
        content_css: 
            # - 'http://localhost/WebITRF/web/bundles/rsitemplate/css/rsi.css'
            # - 'http://localhost/WebITRF/web/bundles/itrfwebsite/css/itrf.css'
        plugin: "hr link table save print anchor searchreplace fullscreen charmap visualblocks image media nonbreaking autolink advlist contextmenu"
        toolbar1: "save | undo redo | removeformat | styleselect | fullscreen print | cut copy paste | searchreplace | hr anchor link table charmap visualblocks nonbreaking"
        toolbar2: "bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist | outdent indent blockquote | subscript superscript"
        contextmenu: "bold italic underline strikethrough | link image inserttable | cell row column deletetable"
        tools: "inserttable"
        nonbreaking_force_tab: true
        save_enablewhendirty: true
        # Le symbole "|" sur la première ligne est très important !! Il permet de predre la suite pour une chaine et non du contenu YML et de préserver les saut de ligne.
        style_formats: |
            [
                {title: 'Titre 1', block: 'h2'},
                {title: 'Titre 2', block: 'h3'},
                {title: 'Titre 3', block: 'h4'},
                {title: 'Important', inline: 'span', styles: {color: '#ff0000'}},
                {title: 'Paragraphe important', block: 'p', classes: 'important'},
                {title: 'Paragraphe normal', block: 'p'}
            ]

jms_translation:
    locales: [en, fr]
    tinymce_mod: []
    configs:
        app:
            dirs: ['@ElsassSeeraiwerESDemoBundle']
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: [*TestCase.php, *Test.php, *.php]
            excluded_dirs: [cache, data, logs]
            default_output_format: xliff
            keep: true
            # extractors: [alias_of_the_extractor]

stof_doctrine_extensions:
    default_locale: en
    orm:
        default:
            sluggable: true

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension