jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: sgn_devblog_blog_index
            logout:
                path: fos_user_security_logout
                target: sgn_devblog_blog_index
            remember_me:
                key:        %secret%
            anonymous:    true

    access_control:
        - { path: ^/[a-z][a-z]/login$,            role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/login_check$,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/register,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/resetting,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z][a-z]/article/,          role: ROLE_DEV }
        - { path: ^/[a-z][a-z]/_trans/,           role: ROLE_TRANSLATION }
        - { path: ^/[a-z][a-z]/menu/,             role: ROLE_MENU }
        - { path: ^/,                             role: IS_AUTHENTICATED_ANONYMOUSLY } 

    role_hierarchy:
        ROLE_TRANSLATION: ROLE_USER
        ROLE_MENU:        ROLE_USER
        ROLE_ARTICLE:     ROLE_USER
        ROLE_DEV:         [ROLE_USER, ROLE_ARTICLE]
        ROLE_DEV_ADMIN:   ROLE_DEV
        ROLE_ADMIN:       [ROLE_USER, ROLE_DEV_ADMIN, ROLE_TRANSLATION, ROLE_MENU]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]