<?php

namespace SGN\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findAllUtilisateur()
	{
		$em = $this->getEntityManager();

		$query = $em->createQuery("SELECT u FROM SGNUserBundle:User u LEFT JOIN u.unite a WHERE u.categorie = '1-UTILISATEUR' ORDER BY a.username ASC, u.username ASC");

		$result = $query->getResult();

		return $result;
	}

	public function findAllUnitUtilisateur($unit)
	{
		$em = $this->getEntityManager();

		$query = $em->createQuery("SELECT u FROM SGNUserBundle:User u LEFT JOIN u.unite a WHERE a.username = '".$unit."' AND u.categorie = '1-UTILISATEUR' ORDER BY a.username ASC, u.username ASC");

		$result = $query->getResult();

		return $result;
	}
}